
import React, { useState } from 'react';
import Card from '../../../components/ui/Card';
import Badge from '../../../components/ui/Badge';
import Button from '../../../components/ui/Button';

const SEOFilesGenerator: React.FC = () => {
  const [pages, setPages] = useState([
    { name: 'Home', checked: true, locked: false, icon: 'description' },
    { name: 'About', checked: true, locked: false, icon: 'info' },
    { name: 'Products', checked: true, locked: false, icon: 'shopping_bag' },
    { name: 'Admin', checked: false, locked: true, icon: 'lock' },
    { name: 'Blog', checked: true, locked: false, icon: 'article' },
  ]);

  const sitemapCode = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://studiobuilder.ai/</loc>
    <lastmod>2023-11-24</lastmod>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://studiobuilder.ai/about</loc>
    <lastmod>2023-11-20</lastmod>
    <priority>0.8</priority>
  </url>
  <!-- Additional 6 pages omitted for brevity -->
</urlset>`;

  const robotsCode = `# Robots.txt generated by StudioBuilder AI

User-agent: *
Allow: /
Disallow: /admin/
Disallow: /api/auth/
Disallow: /temp/

Sitemap: https://studiobuilder.ai/sitemap.xml
Crawl-delay: 10`;

  return (
    <div className="h-full flex flex-col bg-[#050810] text-slate-300 font-sans overflow-hidden">
      
      {/* 1. INTERNAL HEADER */}
      <header className="h-16 border-b border-white/5 bg-[#0c111d] flex items-center justify-between px-8 shrink-0 z-50">
        <div className="flex items-center gap-4">
           <div className="flex items-center gap-3 text-xs font-bold text-slate-500">
              <div className="w-6 h-6 bg-primary/20 rounded flex items-center justify-center text-primary">
                 <span className="material-icons-round text-sm">architecture</span>
              </div>
              <span className="hover:text-white cursor-pointer transition-colors">Projects</span>
              <span className="material-icons-round text-[10px] opacity-30">chevron_right</span>
              <span className="hover:text-white cursor-pointer transition-colors">Portfolio-v1</span>
              <span className="material-icons-round text-[10px] opacity-30">chevron_right</span>
              <span className="text-white">SEO Settings</span>
           </div>
        </div>

        <div className="flex items-center gap-6">
           <div className="flex items-center gap-2 px-3 py-1.5 bg-emerald-500/5 border border-emerald-500/20 rounded-full">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
              <span className="text-[9px] font-black text-emerald-500 uppercase tracking-widest">Live Sync Active</span>
           </div>
           
           <button className="flex items-center gap-2 px-6 py-2 bg-primary text-white rounded-xl text-[10px] font-black shadow-xl shadow-primary/30 hover:scale-105 transition-all uppercase tracking-widest">
              <span className="material-icons-round text-sm">save</span>
              Save to Root Folder
           </button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto custom-scrollbar p-10 space-y-12">
        
        {/* Title Section */}
        <div className="flex justify-between items-start">
           <div className="space-y-2">
              <h1 className="text-3xl font-black text-white tracking-tight">Technical SEO Files</h1>
              <p className="text-slate-500 font-medium">Configure automated discovery and crawling rules for search engine bots.</p>
           </div>
           <div className="flex gap-3">
              <button className="px-5 py-2.5 bg-primary/10 border border-primary/20 text-primary text-[10px] font-black uppercase rounded-xl hover:bg-primary/20 transition-all">Sitemap Settings</button>
              <button className="px-5 py-2.5 bg-white/5 border border-white/10 text-slate-400 text-[10px] font-black uppercase rounded-xl hover:text-white transition-all">Validation History</button>
           </div>
        </div>

        {/* 2. SITEMAP PAGE INCLUSION PANEL */}
        <Card className="p-8 bg-[#0c111d] border-white/5 rounded-[32px] space-y-8">
           <div className="flex justify-between items-center">
              <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500">Sitemap Page Inclusion</h3>
              <span className="text-[10px] font-bold text-slate-600">8 of 10 pages included</span>
           </div>

           <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
              {pages.map((p, i) => (
                 <div 
                   key={p.name}
                   className={`p-4 rounded-2xl border-2 transition-all flex items-center justify-between group cursor-pointer ${
                     p.locked ? 'bg-black/20 border-white/5 opacity-50 cursor-not-allowed' : 
                     p.checked ? 'border-primary/40 bg-primary/5' : 'border-white/5 bg-white/5 hover:border-white/20'
                   }`}
                 >
                    <div className="flex items-center gap-3">
                       <span className={`material-icons-round text-sm ${p.checked ? 'text-primary' : 'text-slate-600'}`}>{p.icon}</span>
                       <span className={`text-xs font-bold ${p.checked ? 'text-white' : 'text-slate-500'}`}>{p.name}</span>
                    </div>
                    {!p.locked && (
                       <div className={`w-5 h-5 rounded-md border-2 flex items-center justify-center transition-all ${p.checked ? 'bg-primary border-primary' : 'border-slate-700'}`}>
                          {p.checked && <span className="material-icons-round text-white text-[12px] font-black">check</span>}
                       </div>
                    )}
                 </div>
              ))}
           </div>
        </Card>

        {/* 3. DUAL EDITORS GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
           {/* Sitemap.xml Editor */}
           <Card className="bg-[#0c111d] border-white/5 rounded-[32px] overflow-hidden flex flex-col shadow-2xl">
              <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-black/20">
                 <div className="flex items-center gap-3">
                    <span className="material-icons-round text-amber-500 text-lg">code</span>
                    <h4 className="text-[10px] font-black uppercase tracking-widest text-white">sitemap.xml</h4>
                    <Badge variant="primary" className="bg-primary/10 border-none text-[8px] px-2">XML</Badge>
                 </div>
                 <div className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>
                    <span className="text-[9px] font-black text-emerald-500 uppercase">Up to Date</span>
                 </div>
              </div>
              <div className="flex-1 p-6 font-mono text-[11px] leading-relaxed bg-black/40 min-h-[360px] overflow-x-auto">
                 <div className="flex gap-4">
                    <div className="text-slate-800 text-right select-none pr-4 border-r border-white/5 min-w-[32px]">
                       {Array.from({length: 14}).map((_, i) => <div key={i}>{(i+1).toString().padStart(2, '0')}</div>)}
                    </div>
                    <div className="flex-1 whitespace-pre text-slate-500">
                       {sitemapCode.split('\n').map((line, i) => {
                         // Simple color highligthing mock
                         const isTag = line.includes('<') || line.includes('>');
                         return (
                           <div key={i} className={isTag ? "text-slate-500" : "text-primary"}>
                             {line.split(/(<[^>]+>)/).map((part, j) => (
                               <span key={j} className={part.startsWith('<') ? "text-primary" : "text-emerald-400"}>{part}</span>
                             ))}
                           </div>
                         );
                       })}
                    </div>
                 </div>
              </div>
              <div className="p-4 border-t border-white/5 flex items-center justify-between bg-black/20">
                 <button className="flex items-center gap-2 text-[9px] font-black uppercase text-slate-500 hover:text-white transition-colors">
                    <span className="material-icons-round text-sm">refresh</span>
                    Regenerate Sitemap
                 </button>
                 <button className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-[9px] font-black uppercase text-white hover:bg-white/10 transition-all">
                    <span className="material-icons-round text-sm">content_copy</span>
                    Copy Code
                 </button>
              </div>
           </Card>

           {/* Robots.txt Editor */}
           <Card className="bg-[#0c111d] border-white/5 rounded-[32px] overflow-hidden flex flex-col shadow-2xl">
              <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between bg-black/20">
                 <div className="flex items-center gap-3">
                    <span className="material-icons-round text-primary text-lg">smart_toy</span>
                    <h4 className="text-[10px] font-black uppercase tracking-widest text-white">robots.txt</h4>
                    <Badge variant="primary" className="bg-primary/10 border-none text-[8px] px-2">TEXT</Badge>
                 </div>
                 <div className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-slate-600"></span>
                    <span className="text-[9px] font-black text-slate-600 uppercase">Saved Local</span>
                 </div>
              </div>
              <div className="flex-1 p-6 font-mono text-[11px] leading-relaxed bg-black/40 min-h-[360px] overflow-x-auto">
                 <div className="flex gap-4">
                    <div className="text-slate-800 text-right select-none pr-4 border-r border-white/5 min-w-[32px]">
                       {Array.from({length: 10}).map((_, i) => <div key={i}>{(i+1).toString().padStart(2, '0')}</div>)}
                    </div>
                    <div className="flex-1 whitespace-pre">
                       {robotsCode.split('\n').map((line, i) => {
                         const isComment = line.startsWith('#');
                         const isKey = line.includes(':');
                         return (
                           <div key={i} className={isComment ? "text-slate-600 italic" : "text-white"}>
                             {isKey ? (
                               <>
                                 <span className="text-rose-400">{line.split(':')[0]}:</span>
                                 <span className="text-white">{line.split(':')[1]}</span>
                               </>
                             ) : line}
                           </div>
                         );
                       })}
                    </div>
                 </div>
              </div>
              <div className="p-4 border-t border-white/5 flex items-center justify-between bg-black/20">
                 <button className="flex items-center gap-2 text-[9px] font-black uppercase text-slate-500 hover:text-white transition-colors">
                    <span className="material-icons-round text-sm">history</span>
                    Reset to Defaults
                 </button>
                 <button className="flex items-center gap-2 px-4 py-2 bg-white/5 border border-white/10 rounded-xl text-[9px] font-black uppercase text-white hover:bg-white/10 transition-all">
                    <span className="material-icons-round text-sm">content_copy</span>
                    Copy Rules
                 </button>
              </div>
           </Card>
        </div>

        {/* 4. FOOTER INFO */}
        <div className="flex flex-col md:flex-row items-center justify-between pt-8 border-t border-white/5 gap-6">
           <div className="flex items-center gap-8">
              <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 hover:text-primary transition-colors cursor-pointer">
                 <span className="material-icons-round text-sm">help_outline</span>
                 Sitemap Documentation
              </div>
              <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 hover:text-primary transition-colors cursor-pointer">
                 <span className="material-icons-round text-sm">verified</span>
                 SEO Best Practices
              </div>
           </div>
           
           <p className="text-[10px] font-bold text-slate-600 italic">All files are automatically minified upon deployment.</p>
        </div>
      </main>

      {/* Collaboration Status Bar */}
      <footer className="h-14 border-t border-white/5 bg-[#090b14] px-8 flex items-center justify-between shrink-0">
         <div className="flex items-center gap-4">
            <div className="flex -space-x-3">
               <img src="https://picsum.photos/seed/seo-1/100/100" className="w-8 h-8 rounded-full border-2 border-[#090b14]" alt="Avatar" />
               <img src="https://picsum.photos/seed/seo-2/100/100" className="w-8 h-8 rounded-full border-2 border-[#090b14]" alt="Avatar" />
            </div>
            <div className="flex items-center gap-2">
               <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full"></div>
               <p className="text-[10px] font-bold text-slate-400">Editing with <span className="text-white">Marketing Team</span></p>
            </div>
         </div>
         <div className="flex items-center gap-3">
            <span className="material-icons-round text-slate-700 text-sm">history</span>
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-widest">Last change 2m ago</p>
         </div>
      </footer>
    </div>
  );
};

export default SEOFilesGenerator;
