
import React, { useState } from 'react';

const FAQPage: React.FC = () => {
  const [active, setActive] = useState<number | null>(0);

  const questions = [
    { q: "How does the autonomous agent work?", a: "Our agents use advanced LLMs fine-tuned on millions of production repositories to architect systems following industry best practices." },
    { q: "Who owns the code generated by StudioBuilder AI?", a: "You own 100% of the custom source code. We provide the infrastructure and intelligence; you retain the intellectual property." },
    { q: "Can I migrate my projects away from the platform?", a: "Yes, we support one-click GitHub exports and containerized deployments that can run on any major cloud provider." },
    { q: "Is there human oversight?", a: "Our highest tier plans include mandatory human validation for all critical system changes before they reach production." }
  ];

  return (
    <div className="max-w-4xl mx-auto px-8 py-24">
      <h1 className="text-5xl font-extrabold mb-12 text-center">Frequently Asked</h1>
      <div className="space-y-4">
        {questions.map((item, i) => (
          <div key={i} className="bg-white/5 border border-white/10 rounded-2xl overflow-hidden">
            <button 
              onClick={() => setActive(active === i ? null : i)}
              className="w-full px-8 py-6 text-left flex justify-between items-center hover:bg-white/5 transition-colors"
            >
              <span className="font-bold">{item.q}</span>
              <span className="material-icons-round transition-transform" style={{ transform: active === i ? 'rotate(180deg)' : 'none' }}>expand_more</span>
            </button>
            {active === i && (
              <div className="px-8 pb-8 text-slate-400 text-sm leading-relaxed animate-in slide-in-from-top-2">
                {item.a}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default FAQPage;
